### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by BoyfriendGltichy472** [i-winxd/FnF-Spritesheet-to-PNG-seq#4]
it can only give 40 images cut from the spritesheet

**Comment by BoyfriendGltichy472** [comment]
well only of theres more than 40 frames in an animation

**Comment by i-winxd** [comment]
That is hardcoded. This is to prevent this program from exporting way too many image files. If you want to increase the number of frames this program can export, you are always welcome to change the source code.

I may increase the limit in the future.

**Comment by BoyfriendGltichy472** [comment]
but how do i turn the source code to a jar

**Comment by BoyfriendGltichy472** [comment]
i just turn it to zip then change extension to jar?

**Comment by BoyfriendGltichy472** [comment]
you should make the limit to 200 because there are the cutscenes and the cutscene xml say that its an idle animation

**Comment by i-winxd** [comment]
Increased the limit to 999,999 for all. Check the new release.
